server:
  port: ${SERVER-PORT:8080}

spring:
  datasource:
    url: jdbc:mysql://${DB-URL}/outsourcing
    username: ${DB-USER}
    password: ${DB-PASSWORD}
    driver-class-name: com.mysql.cj.jdbc.Driver

  sql:
    init:
      encoding: UTF-8

  jpa:
    hibernate:
      ddl-auto: ${DDL-AUTO}
    properties:
      hibernate:
        #show_sql: true
        format_sql: true
        connection:
          CharSet: utf-8
          characterEncoding: utf-8
          useUnicode: true

logging.level:
  root: info
#  org.hibernate.SQL: debug
#  org.springframework.security: debug
#  org.springframework.web: debug

jwt-secret-key: ${JWT-SECRET-KEY}

admin-password: ${ADMIN-PASSWORD}